// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADzafsh0vkENJYu6rqzllbzb2FLKjvy5s',
    appId: '1:215018514801:web:dc56068f883119480a6ed0',
    messagingSenderId: '215018514801',
    projectId: 'taller3-15524',
    authDomain: 'taller3-15524.firebaseapp.com',
    storageBucket: 'taller3-15524.firebasestorage.app',
    measurementId: 'G-80ZE53B0QK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJDbprwgyuIWItwPBT4ExiYJpkSpCmxK4',
    appId: '1:215018514801:android:f760a92670c1f2a20a6ed0',
    messagingSenderId: '215018514801',
    projectId: 'taller3-15524',
    storageBucket: 'taller3-15524.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1S4LF511yNcqvunhOlyovdktSFa6NXQE',
    appId: '1:215018514801:ios:5a7222753d6643da0a6ed0',
    messagingSenderId: '215018514801',
    projectId: 'taller3-15524',
    storageBucket: 'taller3-15524.firebasestorage.app',
    iosBundleId: 'com.example.talleresmoviles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1S4LF511yNcqvunhOlyovdktSFa6NXQE',
    appId: '1:215018514801:ios:5a7222753d6643da0a6ed0',
    messagingSenderId: '215018514801',
    projectId: 'taller3-15524',
    storageBucket: 'taller3-15524.firebasestorage.app',
    iosBundleId: 'com.example.talleresmoviles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADzafsh0vkENJYu6rqzllbzb2FLKjvy5s',
    appId: '1:215018514801:web:114222e18950596d0a6ed0',
    messagingSenderId: '215018514801',
    projectId: 'taller3-15524',
    authDomain: 'taller3-15524.firebaseapp.com',
    storageBucket: 'taller3-15524.firebasestorage.app',
    measurementId: 'G-ZERDPWWGW1',
  );
}
